-- Ukázková data. Ceny, gramáže a složení jsou placeholdery, před spuštěním se nahradí daty od výrobců.
insert into products (slug, line, variant, animals, storage, weight_grams, price_czk, original_price_czk, producer, intro, composition, storage_note, dosage, in_stock, is_new, sort_order, is_published)
values
('zaklad-hovezi-mix', 'zaklad', 'hovězí mix', '{pes}', 'mrazene', 1000, 89, null, '[VÝROBCE]', 'Kompletní hovězí mix pro psy všech velikostí. Dobrý začátek pro toho, kdo s BARFem začíná.', '[SLOŽENÍ OD VÝROBCE] hovězí svalovina, hovězí dršťky, hovězí srdce, masité kosti.', 'Skladujte v mrazáku při −18 °C. Rozmrazujte v lednici, rozmražené spotřebujte do 48 hodin.', 'Dospělý pes zhruba 2–3 % hmotnosti těla denně. Dvacetikilový pes tedy 400–600 g.', true, false, 0, true),
('zaklad-drubezi-mix', 'zaklad', 'drůbeží mix', '{pes,kocka}', 'mrazene', 1000, 69, null, '[VÝROBCE]', 'Lehčí kuřecí mix pro psy i kočky. Vhodný pro citlivější zažívání a pro seniory.', '[SLOŽENÍ OD VÝROBCE] kuřecí maso s kostí, kuřecí krky, kuřecí játra.', 'Skladujte v mrazáku při −18 °C. Rozmrazujte v lednici, rozmražené spotřebujte do 48 hodin.', 'Pes 2–3 % hmotnosti denně, kočka zhruba 40–60 g na kilo hmotnosti týdně.', true, false, 10, true),
('zaklad-kruti-mix', 'zaklad', 'krůtí mix', '{pes,kocka}', 'mrazene', 500, 45, null, '[VÝROBCE]', 'Krůtí mix v půlkilovém balení. Praktické pro kočky a malé psy.', '[SLOŽENÍ OD VÝROBCE] krůtí maso, krůtí krky, krůtí žaludky.', 'Skladujte v mrazáku při −18 °C. Rozmrazujte v lednici, rozmražené spotřebujte do 48 hodin.', 'Kočka zhruba 40–60 g na kilo hmotnosti týdně, malý pes 2–3 % hmotnosti denně.', true, true, 20, true),
('zaklad-jehneci-mix', 'zaklad', 'jehněčí mix', '{pes}', 'mrazene', 1000, 129, null, '[VÝROBCE]', 'Jehněčí mix pro psy, kterým nesedí hovězí ani kuře. Bývá ho málo, když je, berte.', '[SLOŽENÍ OD VÝROBCE] jehněčí maso, jehněčí kosti, jehněčí plíce.', 'Skladujte v mrazáku při −18 °C. Rozmrazujte v lednici, rozmražené spotřebujte do 48 hodin.', 'Dospělý pes zhruba 2–3 % hmotnosti těla denně.', false, false, 30, true),
('zaklad-rybi-mix', 'zaklad', 'rybí mix', '{pes,kocka}', 'mrazene', 500, 59, 69, '[VÝROBCE]', 'Mix z celých mořských ryb. Jednou až dvakrát týdně místo masa, kvůli omega-3.', '[SLOŽENÍ OD VÝROBCE] sleď, makrela, treska (celé ryby).', 'Skladujte v mrazáku při −18 °C. Rozmrazujte v lednici, rozmražené spotřebujte do 24 hodin.', 'Jednou až dvakrát týdně jako náhrada masité dávky.', true, false, 40, true),
('kosti-kureci-krky', 'kosti', 'kuřecí krky', '{pes,kocka}', 'mrazene', 1000, 49, null, '[VÝROBCE]', 'Měkké masité kosti pro malé psy, štěňata a kočky. První kost, kterou dáváme začátečníkům.', '[SLOŽENÍ OD VÝROBCE] kuřecí krky 100 %.', 'Skladujte v mrazáku při −18 °C. Podávejte rozmražené nebo lehce namražené.', 'Jako část denní dávky, kosti mají dělat zhruba 10–15 % krmiva.', true, false, 50, true),
('kosti-hovezi-zebra', 'kosti', 'hovězí žebra', '{pes}', 'mrazene', 1000, 79, null, '[VÝROBCE]', 'Masitá hovězí žebra pro střední a velké psy. Na dlouhé hryzání, ne na spolknutí.', '[SLOŽENÍ OD VÝROBCE] hovězí žebra s masem 100 %.', 'Skladujte v mrazáku při −18 °C. Nikdy nevařte, vařené kosti se štípou.', 'Jedno až dvě žebra podle velikosti psa, vždy pod dohledem.', true, false, 60, true),
('kosti-kachni-kridla', 'kosti', 'kachní křídla', '{pes}', 'mrazene', 1000, 65, null, '[VÝROBCE]', 'Kachní křídla pro střední psy. Tučnější než kuřecí, dobré na zimu.', '[SLOŽENÍ OD VÝROBCE] kachní křídla 100 %.', 'Skladujte v mrazáku při −18 °C. Podávejte rozmražené.', 'Jako část denní dávky, kosti mají dělat zhruba 10–15 % krmiva.', true, true, 70, true),
('navic-lososovy-olej', 'navic', 'lososový olej', '{pes,kocka}', 'chlazene', 250, 189, null, '[VÝROBCE]', 'Lososový olej na srst a klouby. Po otevření patří do lednice.', '[SLOŽENÍ OD VÝROBCE] lososový olej 100 %, lisovaný za studena.', 'Neotevřený v temnu, po otevření v lednici a spotřebovat do 6 týdnů.', 'Zhruba 1 ml na 5 kg hmotnosti denně, přidat do misky.', true, false, 80, true),
('navic-bylinna-smes', 'navic', 'bylinná směs', '{pes}', 'suche', 150, 149, null, '[VÝROBCE]', 'Sušené byliny do mixu. Kopřiva, pampeliška, petržel a další.', '[SLOŽENÍ OD VÝROBCE] kopřiva, pampeliška, petržel, heřmánek.', 'V suchu a temnu, uzavřené. Spotřeba do 12 měsíců.', 'Špetka až lžička denně podle velikosti psa, zamíchat do masa.', true, false, 90, true),
('navic-zeleninovy-mix', 'navic', 'zeleninový mix', '{pes}', 'mrazene', 500, 39, null, '[VÝROBCE]', 'Rozmixovaná zelenina k masu. Pro psy, kteří potřebují víc vlákniny.', '[SLOŽENÍ OD VÝROBCE] mrkev, cuketa, jablko, špenát.', 'Skladujte v mrazáku při −18 °C. Rozmražené spotřebujte do 48 hodin.', 'Zhruba 10 % denní dávky, zamíchat do masa.', true, false, 100, true),
('mlsky-susene-hovezi-plice', 'mlsky', 'sušené hovězí plíce', '{pes,kocka}', 'suche', 100, 79, null, '[VÝROBCE]', 'Lehké, křupavé, dobře se lámou. Odměna na trénink pro psy i kočky.', '[SLOŽENÍ OD VÝROBCE] hovězí plíce 100 %.', 'V suchu, uzavřené. Spotřeba do 12 měsíců.', 'Pár kousků denně. Pamlsky počítejte do denní dávky.', true, false, 110, true),
('mlsky-susene-kureci-prsa', 'mlsky', 'sušená kuřecí prsa', '{pes,kocka}', 'suche', 100, 99, null, '[VÝROBCE]', 'Sušené kuřecí maso v plátcích. Jedna surovina, nic dalšího.', '[SLOŽENÍ OD VÝROBCE] kuřecí prsa 100 %.', 'V suchu, uzavřené. Spotřeba do 12 měsíců.', 'Pár kousků denně. Pamlsky počítejte do denní dávky.', true, false, 120, true),
('mlsky-hovezi-kuze', 'mlsky', 'hovězí kůže', '{pes}', 'suche', 200, 119, 139, '[VÝROBCE]', 'Sušená hovězí kůže na dlouhé žvýkání. Pro psy, kteří potřebují něco do zubů.', '[SLOŽENÍ OD VÝROBCE] hovězí kůže 100 %.', 'V suchu, uzavřené. Spotřeba do 12 měsíců.', 'Jeden kus, pod dohledem.', true, false, 130, true)
on conflict (slug) do nothing;
